export const prompts = [
    "Generate a quote from Albert Einstein",
    "Generate a quote from Mahatma Gandhi",
    "Generate a quote from Abraham Lincoln",
    "Generate a quote from Winston Churchill",
    "Generate a quote from Martin Luther King Jr.",
    "Generate a quote from Nelson Mandela",
    "Generate a quote from Steve Jobs",
    "Generate a quote from Maya Angelou",
    "Generate a quote from Mother Teresa",
    "Generate a quote from Mark Twain",
    "Generate a quote from Coco Chanel",
    "Generate a quote from Ernest Hemingway",
    "Generate a quote from Oprah Winfrey",
    "Generate a quote from Leonardo da Vinci",
    "Generate a quote from Albert Camus",
    "Generate a quote from William Shakespeare",
    "Generate a quote from Eleanor Roosevelt",
    "Generate a quote from Pablo Picasso",
    "Generate a quote from Isaac Newton",
    "Generate a quote from Rosa Parks",
    "Generate a quote from Charles Darwin",
    "Generate a quote from Marie Curie",
    "Generate a quote from Vincent van Gogh",
    "Generate a quote from Helen Keller",
    "Generate a quote from Johann Wolfgang von Goethe",
    "Generate a quote from Socrates",
    "Generate a quote from Nikola Tesla",
    "Generate a quote from Benjamin Franklin",
    "Generate a quote from Confucius",
    "Generate a quote from Walt Disney",
    "Generate a quote from Stephen Hawking",
    "Generate a quote from Albert Schweitzer",
    "Generate a quote from Dalai Lama",
    "Generate a quote from Henry Ford",
    "Generate a quote from Anne Frank",
    "Generate a quote from Bruce Lee",
    "Generate a quote from Winston Churchill",
    "Generate a quote from Audrey Hepburn",
    "Generate a quote from Thomas Edison",
    "Generate a quote from Amelia Earhart",
    "Generate a quote from Genghis Khan",
    "Generate a quote from Marie Antoinette",
    "Generate a quote from Malcolm X",
    "Generate a quote from Vincent Lombardi",
    "Generate a quote from Winston Churchill",
    "Generate a quote from Marie Curie",
    "Generate a quote from Princess Diana",
    "Generate a quote from Alexander the Great",
    "Generate a quote from Theodore Roosevelt",
    "Generate a quote from John F. Kennedy",
    "Generate a quote from Benjamin Disraeli",
    "Generate a quote from George Orwell",
    "Generate a quote from Neil Armstrong",
    "Generate a quote from Margaret Thatcher",
    "Generate a quote from Julius Caesar",
    "Generate a quote from Galileo Galilei",
    "Generate a quote from Bill Gates",
    "Generate a quote from Henry Kissinger",
    "Generate a quote from Elon Musk",
    "Generate a quote from Marie Curie",
    "Generate a quote from Jane Austen",
    "Generate a quote from Michelangelo",
    "Generate a quote from Mahatma Gandhi",
    "Generate a quote from John Lennon",
    "Generate a quote from Aristotle",
    "Generate a quote from Ernest Hemingway",
    "Generate a quote from Marie Curie",
    "Generate a quote from Taras Shevchenko",
    "Generate a quote from Ivan Franko",
    "Generate a quote from Lesia Ukrainka",
    "Generate a quote from Bohdan Khmelnytskyi",
    "Generate a quote from Stepan Bandera",
    "Generate a quote from Volodymyr Vernadskyi",
    "Generate a quote from Igor Sikorskyi",
    "Generate a quote from Vasyl Stus",
    "Generate a quote from Ivan Mazepa",
    "Generate a quote from Sergei Korolev",
    "Generate a quote from Mykhailo Hrushevskyi",
    "Generate a quote from Valeriy Lobanovskyi",
    "Generate a quote from Mykola Amosov",
    "Generate a quote from Volodymyr Zelenskyi",
    "Generate a quote from Lina Kostenko",
    "Generate a quote from Oleksandr Usyk",
    "Generate a quote from Oleh Blokhin",
    "Generate a quote from Serhiy Rebrov",
    "Generate a quote from Volodymyr Klitschko",
    "Generate a quote from Vitaliy Klitschko",
    "Generate a quote from Yaroslav the Wise",
    "Generate a quote from Levko Lukyanenko",
    "Generate a quote from Bohdan Hawrylyshyn",
    "Generate a quote from Yevhen Konovalets",
    "Generate a quote from Ivan Mykolaichuk",
    "Generate a quote from Vasyl Lomachenko",
    "Generate a quote from Mykhailo Kotsyubynsky",
    "Generate a quote from Dmytro Yavornytsky",
    "Generate a quote from Bohdan Stupka",
    "Generate a quote from Les Kurbas",
    "Generate a quote from Oleh Tyahnybok",
    "Generate a quote from Oleksandr Dovzhenko",
    "Generate a quote from Vasyl Symonenko",
    "Generate a quote from Viacheslav Chornovil",
    "Generate a quote from Hryhorii Skovoroda",
];
